name: Scaffold
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - "develop"

# Terraform jobs are queued per branch to prevent
# concurrent actions on the same Terraform workspace
concurrency: 
  group: ci-${{ github.ref }}


jobs:
  namespace:
    if: github.event.pull_request.draft == false
    name: Scaffold things
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  