name: Scaffold + deploy
on:
  push:
    branches:
      - main

# Terraform jobs are queued per branch to prevent
# concurrent actions on the same Terraform workspace
concurrency: 
  group: ci-${{ github.ref }}

jobs:
  namespace:
    if: github.event.pull_request.draft == false
    name: Scaffold
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
    - uses: actions/checkout@v3
  deployment:
    name: Deploy
    needs: [namespace]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://${{ github.ref }}.test.com
    steps:
    - uses: actions/checkout@v3
  